{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 1", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很giao的测试用例\")\n    def test_3():\n>       assert 0 > 1\nE       assert 0 > 1\n\ntest_1.py:17: AssertionError"}, "start": 1566179220234, "stop": 1566179220234, "uuid": "0fb652e9-961e-4af4-afe8-f7d317a7f17e", "historyId": "5573ca69ec5a612ab6ebd2e4e95d945e", "fullName": "test_1#test_3", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这是一个很giao的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "sunzl"}, {"name": "thread", "value": "4016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}