{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'giao哥牛逼' in '牛逼'", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个特别giao的测试用例\")\n    def test_4():\n        \"\"\"\n        这是一个一giao我哩giao的用例\n        \"\"\"\n>       assert \"giao哥牛逼\" in \"牛逼\"\nE       AssertionError: assert 'giao哥牛逼' in '牛逼'\n\ntest_1.py:24: AssertionError"}, "description": "\n    这是一个一giao我哩giao的用例\n    ", "start": 1566181846670, "stop": 1566181846670, "uuid": "c013a0c2-a6fc-43ac-9150-bf89940971d5", "historyId": "c8cd82c99acc944c4aab84b5eddb6ed6", "fullName": "test_1#test_4", "labels": [{"name": "story", "value": "这是一个特别giao的测试用例"}, {"name": "feature", "value": "模块二"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "sunzl"}, {"name": "thread", "value": "7952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}