{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 1", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很giao的测试用例\")\n    def test_3():\n>       assert 0 > 1\nE       assert 0 > 1\n\ntest_1.py:17: AssertionError"}, "start": 1566179196167, "stop": 1566179196167, "uuid": "62e3d5a5-aa16-4c73-8ad9-e4e6d26126ee", "historyId": "5573ca69ec5a612ab6ebd2e4e95d945e", "fullName": "test_1#test_3", "labels": [{"name": "story", "value": "这是一个很giao的测试用例"}, {"name": "feature", "value": "模块二"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "sunzl"}, {"name": "thread", "value": "9860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}